### ISSUE TITLE
Issue in windows app

### ISSUE THREAD

**Issue by abinstanlyns** [Hiteshdon/mssql_connection#10]
updated to 2.0.1 , can't run in windows, below error showing. App can run in version 1.1.3 (but sql connection not work).

database_manager.obj : error LNK2019: unresolved external symbol SQLAllocHandle referenced in function "public: bool __cdecl DatabaseManager::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?connect@DatabaseManager@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0000@Z) [C:\Users\SAPC\StudioProjects\untitled\build\windows\x64\plugins\mssql_connection\mssql_connection_plugin.vcxproj]

**Comment by Hiteshdon** [comment]
If you elaborate the issue, I would appreciate it.

**Comment by abinstanlyns** [comment]
Issue got fixed.
after updating to 2.0.1 , trying to run windows build ,above error is shown. updated flutter and done so many things and did't know which one is worked.
Generated windows build not working in other computer (Only working in the computer where project running).

support for IOS/MACOS 
is highly appreciated.
